apiVersion: v2
appVersion: v0.3.2
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.7.3
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: 8.5.1
  - name: common
    version: 1.3.1
    repository: https://bjw-s.github.io/helm-charts/
description: A Helm chart for Kubernetes
name: tubearchivist
type: application
version: 0.8.3
