apiVersion: v2
name: hello-free-shavacado
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.0-development"
dependencies:
  - name: common
    version: 1.3.1
    repository: https://bjw-s.github.io/helm-charts/
